version: '3'

services:
  route-simulator:
    build: ./route-simulator
    container_name: route-simulator
    networks:
      - code-delivery-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  api:
    build: ./spring-api
    container_name: spring-api
    ports:
      - "8084:8084"
    networks:
      - code-delivery-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  frontend:
    build: ./react-frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - code-delivery-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on: 
      - api

networks:
  code-delivery-network:
    external: true
